version: '3'

services:
  web:
    build: .
    ports:
      - '3020:3020'
    environment:
      - PORT=3020
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS='ben@newton#1996#'
      - MYSQL_DATABASE=todos
  db:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=ben@newton#1996#
      - MYSQL_DATABASE=todos

    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
